SET NDK_HOME=c:\Android\ndk\27.0.12077973\
SET ANDROID_ABI=arm64-v8a
SET ANDROID_PLATFORM=30
SET ANDROID_STL=c++_static
SET BUILD_TYPE=Release
SET INSTALL_PEFIX=install


cmake -G Ninja .. -DCMAKE_TOOLCHAIN_FILE=%NDK_HOME%\build\cmake\android.toolchain.cmake ^
	     -DANDROID_ABI=%ANDROID_ABI% ^
	     -DANDROID_PLATFORM=%ANDROID_PLATFORM% ^
	     -DANDROID_STL=%ANDROID_STL% ^
		 -DCMAKE_BUILD_TYPE=%BUILD_TYPE% ^
		 -DCMAKE_INSTALL_PREFIX=%INSTALL_PEFIX% ^
		 -DANDROID=1
	 
ninja
ninja install
